export const ARTISANS = [
  {
    id: 'ramesh-sharma',
    name: 'Pandit Ramesh Sharma',
    craft: 'Master Terracotta & Blue Glaze Potter',
    location: 'Khurja, Uttar Pradesh',
    generation: '4th Generation Potter',
    experience: '38 years on the wheel',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1200&q=80',
    bio: 'Pandit Ramesh shapes clay using ancient wood-fired kiln techniques passed down through four generations of Khurja potters. Each pot spends 48 hours in the kiln at 1,180°C.',
    quote: 'The clay speaks to your fingers. If you rush it, it cracks in the fire. Slow patience is the only true glaze.',
    badge: 'Heritage Master Craftsman',
    productCount: 14,
    rating: 4.9,
    reviewsCount: 128,
    awards: ['National Handicraft Merit Award 2018', 'UP Craft Ratna 2022'],
    specialty: 'Wood-fired stoneware and speckled tea sets'
  },
  {
    id: 'devika-rathore',
    name: 'Devika & Sumitra Rathore',
    craft: 'Natural Indigo Block Printers',
    location: 'Bagru, Rajasthan',
    generation: '3rd Generation Dabu Artisans',
    experience: '24 years of mud-resist printing',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1606744824163-985d376605aa?auto=format&fit=crop&w=1200&q=80',
    bio: 'Devika and her mother Sumitra lead a collective of 18 women artisans in Bagru. They use 100% plant dyes extracted from pomegranate rinds, madder root, and organic fermented indigo.',
    quote: 'When you wear our block prints, you carry the smell of sun-dried Rajasthani river mud and wild indigo.',
    badge: 'Eco-Craft Pioneer',
    productCount: 22,
    rating: 5.0,
    reviewsCount: 215,
    awards: ['UNESCO Craft Seal of Excellence', 'Fair Trade Artisan Award 2021'],
    specialty: 'Dabu mud resist & 100% natural indigo handloom silks'
  },
  {
    id: 'maniram-kashyap',
    name: 'Maniram Kashyap',
    craft: 'Lost-Wax Bell Metal (Dhokra) Sculptor',
    location: 'Bastar, Chhattisgarh',
    generation: '5th Generation Ghadwa Artisan',
    experience: '32 years',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80',
    bio: 'Maniram practices Dhokra, a 4,000-year-old non-ferrous metal casting technique identical to the Harappan Dancing Girl artifact. Every single wax mold is destroyed in the casting, making each piece strictly one-of-a-kind.',
    quote: 'No two Dhokra pieces in the universe can ever be identical. Each one lives once in bees wax, dies in fire, and is reborn in brass.',
    badge: 'Ancient Lineage Custodian',
    productCount: 9,
    rating: 4.95,
    reviewsCount: 84,
    awards: ['Presidential Bronze Medal 2016'],
    specialty: 'Tribal folklore sculptures & brass bell lamps'
  },
  {
    id: 'mir-bashir',
    name: 'Ustad Mir Bashir Ahmad',
    craft: 'Walnut Wood Chiseler & Lattice Carver',
    location: 'Srinagar, Jammu & Kashmir',
    generation: 'Master Woodwright',
    experience: '45 years of fine carving',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1200&q=80',
    bio: 'Ustad Bashir carves seasoned Himalayan walnut timber dried for 6 years. His delicate pinjrakari (lattice) and floral relief carvings take up to 3 weeks per object without a single electric tool.',
    quote: 'A power tool forces the wood; a hand chisel listens to the grain.',
    badge: 'Master Living Treasure',
    productCount: 11,
    rating: 4.88,
    reviewsCount: 96,
    awards: ['State Master Craftsman 2014'],
    specialty: 'Intricate walnut bookends, spice chests & mirror frames'
  },
  {
    id: 'ananya-menon',
    name: 'Ananya & Gayatri Menon',
    craft: 'Cold-Pressed Botanical Soaper & Herbalist',
    location: 'Wayanad, Kerala',
    generation: '2nd Generation Ayurvedic Botanist',
    experience: '12 years',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=1200&q=80',
    bio: 'Hand-cured for 6 weeks in small batches using virgin coconut oil from their family grove and wild-harvested herbs from the Western Ghats rainforest.',
    quote: 'Pure skincare shouldn’t need a chemistry degree to understand. Just pure rain, coconut milk, and forest herbs.',
    badge: 'Zero Waste & 100% Organic',
    productCount: 18,
    rating: 4.96,
    reviewsCount: 340,
    awards: ['Green Earth Artisan Gold 2023'],
    specialty: 'Raw botanical soaps & sandalwood nourishing balms'
  }
];
