export const PRODUCTS = [
  {
    id: 'khurja-speckled-kulhad-set',
    name: 'Speckled Terracotta Chai Kulhad Set (Pack of 4)',
    slug: 'speckled-terracotta-chai-kulhad-set',
    tagline: 'Hand-thrown on a foot wheel, wood-fired with organic feldspar glaze',
    price: 1450,
    originalPrice: 1800,
    category: 'Pottery & Ceramics',
    location: 'Khurja, Uttar Pradesh',
    material: 'Natural Khurja Clay & Matte Glaze',
    artisanId: 'ramesh-sharma',
    artisanName: 'Pandit Ramesh Sharma',
    artisanAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&q=80',
    primaryImage: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
    hoverImage: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=1000&q=80'
    ],
    rating: 4.9,
    reviewsCount: 48,
    stock: 5,
    batchNo: 'Batch #12 (Fired Aug 2026)',
    leadTime: 'Ships within 48 hours',
    featured: true,
    badges: ['Slow Made', 'Kiln Fresh', 'Only 5 Left'],
    accentColor: '#D95D39',
    description: 'Each cup is thrown individually on a slow foot-wheel in Khurja by Pandit Ramesh. Coated with a raw mineral feldspar glaze that develops unique iron freckles during the 48-hour wood firing cycle. Keeps tea steaming hot while remaining comforting to hold.',
    dimensions: '3.2" H x 2.8" Dia (Holds 180ml)',
    craftingProcess: 'Hand-wedged riverbed clay is turned on a traditional stone wheel, trimmed by hand with bamboo knives, air-dried under jute sacks for 5 days, and fired in an earthen updraft kiln.',
    careInstructions: 'Microwave and dishwasher safe. Hand washing with mild soap preserves the tactile mineral matte exterior.',
    shippingInfo: 'Packed in biodegradable shredded honeycomb paper and coconut coir cushioning. Guaranteed zero plastic.'
  },
  {
    id: 'bagru-dabu-chanderi-dupatta',
    name: 'Dabu Mud-Resist Indigo Handloom Dupatta',
    slug: 'dabu-mud-resist-indigo-chanderi-dupatta',
    tagline: 'Pure Chanderi silk-cotton hand-stamped with teak wood blocks and wild fermented indigo',
    price: 3200,
    originalPrice: 3800,
    category: 'Handloom Textiles',
    location: 'Bagru, Rajasthan',
    material: 'Pure Chanderi (60% Silk, 40% Cotton)',
    artisanId: 'devika-rathore',
    artisanName: 'Devika & Sumitra Rathore',
    artisanAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=120&q=80',
    primaryImage: 'https://images.unsplash.com/photo-1606744824163-985d376605aa?auto=format&fit=crop&w=800&q=80',
    hoverImage: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1606744824163-985d376605aa?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=1000&q=80'
    ],
    rating: 5.0,
    reviewsCount: 76,
    stock: 3,
    batchNo: 'Monsoon Sun-Drying Edition',
    leadTime: 'Ready to ship',
    featured: true,
    badges: ['100% Plant Dye', 'UNESCO Heritage', 'Slow Craft'],
    accentColor: '#204B3B',
    description: 'This gossamer-light Chanderi dupatta is printed using the 400-year-old Dabu technique. A paste of black clay, gum, and saw dust is hand-pressed using hand-carved teak wood stamps before dipping into deep natural indigo vats.',
    dimensions: '2.5 meters length x 36 inches width with hand-knotted zari tassels',
    craftingProcess: 'Stamped 3 times with different resist pastes, sun-dried on riverbed sand, and rinsed in cascading sweet water wells.',
    careInstructions: 'Dry clean only for the first two washes; thereafter gentle hand wash with cold water and mild ph-neutral liquid soap.',
    shippingInfo: 'Hand-wrapped in block-printed cotton muslin gift bags with a handwritten thank you letter from Devika.'
  },
  {
    id: 'dhokra-brass-tribal-dancer',
    name: 'Bastar Lost-Wax Brass Dancing Joy Figurine',
    slug: 'bastar-lost-wax-brass-dancing-joy',
    tagline: 'Ancient 4,000-year-old Ghadwa lost-wax casting technique; strictly one-of-a-kind',
    price: 4600,
    originalPrice: 5200,
    category: 'Metalcraft & Brass',
    location: 'Bastar, Chhattisgarh',
    material: 'Upcycled Bell Metal Brass & Natural Beeswax Mold',
    artisanId: 'maniram-kashyap',
    artisanName: 'Maniram Kashyap',
    artisanAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=120&q=80',
    primaryImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80',
    hoverImage: 'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1000&q=80'
    ],
    rating: 4.95,
    reviewsCount: 32,
    stock: 2,
    batchNo: 'Unique Piece #087',
    leadTime: 'Ships tomorrow',
    featured: true,
    badges: ['One of One', '4,000 Yr Technique', 'Heirloom Piece'],
    accentColor: '#E5A136',
    description: 'A striking heirloom sculpture capturing the celebratory dance of tribal Bastar rituals. The artisan wraps microscopic threads of pure bee-wax over a clay core before covering in river mud and pouring molten brass at 1,000°C.',
    dimensions: '9.5" Height x 4.2" Width x 3.0" Depth. Weight: 1.15 kg.',
    craftingProcess: 'Lost wax casting (Cire Perdue). The clay mold is smashed open to release the sculpture, meaning no duplicate can ever exist.',
    careInstructions: 'Wipe with a dry microfiber cloth. Avoid chemical brass polishes to preserve the antique golden patina.',
    shippingInfo: 'Custom double-boxed with recycled craft corrugation and foam cushion corners.'
  },
  {
    id: 'kashmir-walnut-carved-bookends',
    name: 'Hand-Chiseled Kashmiri Walnut Wood Bookends (Pair)',
    slug: 'kashmiri-walnut-wood-carved-bookends',
    tagline: 'Single block wild walnut timber with traditional Chinar leaf relief work',
    price: 2850,
    originalPrice: 3400,
    category: 'Woodwork & Carving',
    location: 'Srinagar, Jammu & Kashmir',
    material: 'Aged Himalayan Walnut Timber & Beeswax Polish',
    artisanId: 'mir-bashir',
    artisanName: 'Ustad Mir Bashir Ahmad',
    artisanAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=120&q=80',
    primaryImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    hoverImage: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1000&q=80'
    ],
    rating: 4.88,
    reviewsCount: 54,
    stock: 7,
    batchNo: 'Autumn Timber Harvest',
    leadTime: 'Ready to ship',
    featured: true,
    badges: ['Solid Walnut', 'Zero Machinery', 'Fair Trade'],
    accentColor: '#BF4A28',
    description: 'Chiseled from dense, naturally fallen walnut wood from the Dachigam valley. Ustad Bashir carves the delicate veins of Chinar leaves using only seven traditional steel chisels (nehro). Finished with natural beeswax buffing for a velvety tactile touch.',
    dimensions: '7.0" H x 5.5" W x 4.0" D (Pair total weight: 1.8 kg)',
    craftingProcess: 'Timber seasoned for 4 years before 18 hours of hand-carving and agathi stone polishing.',
    careInstructions: 'Wipe with dry cloth. Rub a pea-sized drop of walnut or coconut oil once a year to keep the wood lustrous for decades.',
    shippingInfo: 'Bubble-free kraft wrapped with wood shaving padding.'
  },
  {
    id: 'wayanad-botanical-soap-bundle',
    name: 'Wild Sandalwood & Raw Honey Cold-Cured Soap Bar Trio',
    slug: 'wayanad-botanical-cold-cured-soap-trio',
    tagline: 'Cured for 45 days with wild forest honey, unrefined coconut oil & red sandalwood extract',
    price: 890,
    originalPrice: 1100,
    category: 'Botanicals & Oils',
    location: 'Wayanad, Kerala',
    material: 'Wild Sandalwood, Raw Forest Honey, Virgin Coconut Milk',
    artisanId: 'ananya-menon',
    artisanName: 'Ananya & Gayatri Menon',
    artisanAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=120&q=80',
    primaryImage: 'https://images.unsplash.com/photo-1607006314597-9d7a22dc05a9?auto=format&fit=crop&w=800&q=80',
    hoverImage: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1607006314597-9d7a22dc05a9?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=1000&q=80'
    ],
    rating: 4.97,
    reviewsCount: 142,
    stock: 14,
    batchNo: 'Batch #44 (Cold cured Oct 2026)',
    leadTime: 'Ready to ship',
    featured: true,
    badges: ['100% Organic', 'Palm-Oil Free', 'Vegan'],
    accentColor: '#2E6F56',
    description: 'Slow cold-process soaps handcrafted in Wayanad with cold-pressed coconut oil and unfiltered forest honey collected by indigenous tribes. Yields a rich, creamy lather that softens sun-exposed skin without stripping moisture.',
    dimensions: 'Set of 3 bars (125g each) in seed-paper packaging that grows into basil plants when planted in soil!',
    craftingProcess: '45-day cold saponification preserving active enzymes and natural glycerin.',
    careInstructions: 'Keep on a draining soap dish to extend lifespan.',
    shippingInfo: 'Plantable seed-paper box packed in banana bark twine.'
  },
  {
    id: 'jaipur-blue-pottery-serving-platter',
    name: 'Turquoise Peacock Blue Pottery Serving Platter (12")',
    slug: 'jaipur-blue-pottery-serving-platter',
    tagline: 'Distinctive clay-free quartz pottery hand-painted with cobalt oxide motifs',
    price: 2150,
    originalPrice: 2600,
    category: 'Pottery & Ceramics',
    location: 'Jaipur, Rajasthan',
    material: 'Quartz Powder, Fuller’s Earth, Glass & Natural Pigments',
    artisanId: 'ramesh-sharma',
    artisanName: 'Pandit Ramesh Sharma',
    artisanAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&q=80',
    primaryImage: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=800&q=80',
    hoverImage: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1000&q=80'
    ],
    rating: 4.85,
    reviewsCount: 67,
    stock: 4,
    batchNo: 'Jaipur Heritage Batch #09',
    leadTime: 'Ships in 24 hours',
    featured: false,
    badges: ['Lead Free', 'Traditional Glaze', 'Collector Item'],
    accentColor: '#1F375D',
    description: 'Unlike traditional clay pottery, Jaipur Blue Pottery uses a dough of crushed quartz stone, glass, and plant gum. Hand-painted with fine squirrel-hair brushes with classic Mughal floral and peacock patterns.',
    dimensions: '12" Diameter x 1.5" Rim Depth (Weight: 850g)',
    craftingProcess: 'Cast in open molds, painted freehand, glazed with low-fire flux, and fired once in wood kilns.',
    careInstructions: 'Wipe clean with warm water and damp cloth. Not microwave safe.',
    shippingInfo: 'Custom molded foam corners and rigid 7-ply artisan carton.'
  },
  {
    id: 'saharanpur-sheesham-spice-box',
    name: 'Brass-Inlaid Sheesham Wood Spice Box (9 Compartments)',
    slug: 'brass-inlaid-sheesham-wood-spice-box',
    tagline: 'Hand-carved with pure brass filigree inlays and glass viewing lid',
    price: 1950,
    originalPrice: 2400,
    category: 'Woodwork & Carving',
    location: 'Saharanpur, Uttar Pradesh',
    material: 'Natural Solid Sheesham (Rosewood) & Pure Brass Sheet',
    artisanId: 'mir-bashir',
    artisanName: 'Ustad Mir Bashir Ahmad',
    artisanAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=120&q=80',
    primaryImage: 'https://images.unsplash.com/photo-1590736969955-71cc94801759?auto=format&fit=crop&w=800&q=80',
    hoverImage: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1590736969955-71cc94801759?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1000&q=80'
    ],
    rating: 4.92,
    reviewsCount: 89,
    stock: 8,
    batchNo: 'Hand-Joined Joinery Edition',
    leadTime: 'Ready to ship',
    featured: false,
    badges: ['Zero Nails', 'Solid Rosewood', 'Includes Spoon'],
    accentColor: '#BF4A28',
    description: 'A centerpiece for your kitchen or dining table. Made with seasoned sheesham wood with brass inlays (tarkashi) hammered into pre-chiseled grooves. Includes 9 removable spice cups and a hand-turned wooden measuring spoon.',
    dimensions: '8" x 8" x 2.5" (Includes wooden spoon)',
    craftingProcess: 'Interlocking dovetail joinery without nails, hand-rubbed linseed oil finish.',
    careInstructions: 'Wipe with dry cotton cloth. Do not soak in water.',
    shippingInfo: 'Packed in corrugated protective box.'
  },
  {
    id: 'bengal-kantha-quilted-tote',
    name: 'Vintage Silk Kantha Reversible Quilted Tote Bag',
    slug: 'vintage-silk-kantha-quilted-tote',
    tagline: 'Upcycled vintage silk saris layered with thousands of running hand-stitches',
    price: 1650,
    originalPrice: 2100,
    category: 'Handloom Textiles',
    location: 'Shantiniketan, West Bengal',
    material: 'Upcycled Pure Silk Saris & Organic Cotton Thread',
    artisanId: 'devika-rathore',
    artisanName: 'Devika & Sumitra Rathore',
    artisanAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=120&q=80',
    primaryImage: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
    hoverImage: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=1000&q=80'
    ],
    rating: 4.87,
    reviewsCount: 45,
    stock: 6,
    batchNo: 'Shantiniketan Women Collective',
    leadTime: 'Ready to ship',
    featured: false,
    badges: ['Upcycled Silk', '10,000+ Stitches', 'Reversible'],
    accentColor: '#D95D39',
    description: 'Every tote is completely unique, pieced together from vintage silk saris hand-stitched by women in rural Bengal. Takes 4 full days of continuous hand embroidery. Completely reversible with two distinct color palettes.',
    dimensions: '16" W x 14" H x 4" D (Strap drop: 11")',
    craftingProcess: '6 layers of vintage silk joined with dense Kantha running needlework.',
    careInstructions: 'Spot clean or hand wash gently in cold water. Air dry in shade.',
    shippingInfo: 'Folded in craft paper with artisan origin certificate.'
  }
];

export const CATEGORIES = [
  { id: 'all', name: 'All Slow Crafts', icon: '✨' },
  { id: 'Pottery & Ceramics', name: 'Pottery & Ceramics', icon: '🏺' },
  { id: 'Handloom Textiles', name: 'Handloom Textiles', icon: '🧵' },
  { id: 'Woodwork & Carving', name: 'Woodwork & Carving', icon: '🪵' },
  { id: 'Metalcraft & Brass', name: 'Metalcraft & Brass', icon: '🪔' },
  { id: 'Botanicals & Oils', name: 'Botanicals & Oils', icon: '🌿' },
];
